apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yugabyte-metrics-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yugabyte-metrics-reader-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: yugabyte-metrics-reader
  apiGroup: rbac.authorization.k8s.io
