kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: sqlmesh
subjects:
- kind: ServiceAccount
  name: default
  namespace: sqlmesh
roleRef:
  kind: Role
  name: pod-purger
  apiGroup: rbac.authorization.k8s.io
